### ISSUE TITLE
[enhancement] Basic Authentication

### ISSUE THREAD

**Issue by elliemirabellie** [C9Glax/tranga-website#35]
Hi, could you include a basic login for the website so not everyone with access to the same lan can add stuff to the library? Thank you for the great project.

**Comment by db-2001** [comment]
I'm not too sure why you'd be giving out the url to the tranga-website instance in the first place if you don't want people to have it (as they wouldn't know what they are looking for) but I can look at what it would take to implement basic HTTP authentication on the website side. I'm not too sure what @C9Glax will say about it because I believe their vision for Tranga is that the API side accepts request from everything and anything, not just the website, so I'm not sure how auth would work be able to work across all of those things without extremely complicating it.

**Comment by C9Glax** [comment]
Yea won't implement. 
This software is _**not safe for use on any public networks**_.
It sends data unencrypted, so authentication would be pointless in and of itself.
If you want basic auth, use a reverse proxy that takes that job.
